 Volume in drive C is Windows 
 Volume Serial Number is 607D-315E

 Directory of C:\Users\User

09/22/2022  12:45 PM    <DIR>          .
09/22/2022  12:45 PM    <DIR>          ..
08/17/2022  11:11 AM    <DIR>          .android
08/25/2022  07:31 AM                66 .gitconfig
09/09/2022  06:08 AM                20 .lesshst
07/27/2022  04:12 PM    <DIR>          .ms-ad
08/17/2022  10:08 AM    <DIR>          .vscode
06/13/2022  08:57 AM    <DIR>          3D Objects
06/13/2022  08:57 AM    <DIR>          Contacts
09/22/2022  12:06 PM    <DIR>          Desktop
09/21/2022  12:15 PM    <DIR>          Documents
09/22/2022  12:33 PM    <DIR>          Downloads
06/13/2022  08:57 AM    <DIR>          Favorites
06/13/2022  08:57 AM    <DIR>          Links
08/19/2022  10:23 AM                57 mercurial.ini
06/13/2022  08:57 AM    <DIR>          Music
09/22/2022  09:48 AM    <DIR>          OneDrive
06/13/2022  09:14 AM    <DIR>          Pictures
09/22/2022  12:45 PM                 0 RUN.BAT
09/22/2022  12:22 PM                 0 RUN.BAT.txt
06/13/2022  08:57 AM    <DIR>          Saved Games
07/27/2022  04:13 PM    <DIR>          Searches
08/21/2022  10:54 AM    <DIR>          source
09/22/2022  12:36 PM    <DIR>          TEST123
07/29/2022  08:43 AM    <DIR>          Videos
               5 File(s)            143 bytes
              20 Dir(s)  141,675,335,680 bytes free
